version: '3'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: '!Avato1234!'
      POSTGRES_USER: avato
      POSTGRES_DB: main
    ports:
      - "49159:5432"

volumes:
  db-data:
